name: adb

base: core18

version: '1.0.41'
license: Apache-2.0

summary: Unofficial snap for Android Debug Bridge (adb)
description: |
  Android Debug Bridge (adb) is a versatile command-line tool that lets you communicate with a device. The adb command facilitates a variety of device actions, such as installing and debugging apps, and it provides access to a Unix shell that you can use to run a variety of commands on a device.

grade: stable
confinement: strict

apps:
  adb:
    command: adb
    plugs:
      - adb-support
      - network
      - network-bind

parts:
  adb:
    plugin: dump
    source: https://dl.google.com/android/repository/platform-tools_r30.0.1-linux.zip
    organize:
      platform-tools/adb: usr/bin/
      platform-tools/NOTICE.txt: usr/share/doc/adb/
    stage:
      - usr/bin
      - usr/share/doc/adb

slots:
  adb:
    interface: content
    read:
      - $SNAP/usr/bin
